const ADD_SELECTED_FOOD_TO_DISH = "ADD_SELECTED_FOOD_TO_DISH";
const REMOVE_SELECTED_FOOD_FROM_DISH = "REMOVE_SELECTED_FOOD_FROM_DISH";
const SET_DISH_NAME = "SET_DISH_NAME";
const RESET_DISH_STATE = "RESET_DISH_STATE";
const REMOVE_ALL_SELECTED_FOODS_FROM_DISH =
  "REMOVE_ALL_SELECTED_FOODS_FROM_DISH";

export {
  ADD_SELECTED_FOOD_TO_DISH,
  REMOVE_SELECTED_FOOD_FROM_DISH,
  SET_DISH_NAME,
  RESET_DISH_STATE,
  REMOVE_ALL_SELECTED_FOODS_FROM_DISH,
};
