const CREATE_USER = "CREATE_USER";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";

const CREATE_DAILY_NUTRITION = "CREATE_DAILY_NUTRITION";
const UPDATE_DAILY_NUTRITION = "UPDATE_DAILY_NUTRITION";

const CREATE_WATER_INTAKE = "CREATE_WATER_INTAKE";
const UPDATE_WATER_INTAKE = "UPDATE_WATER_INTAKE";

const CREATE_WATER_REMINDER_NOTIFICATION = "CREATE_WATER_REMINDER_NOTIFICATION";
const CREATE_WATER_REMINDER_NOTIFICATION_LIST =
  "CREATE_WATER_REMINDER_NOTIFICATION_LIST";
const DELETE_WATER_REMINDER_NOTIFICATION = "DELETE_WATER_REMINDER_NOTIFICATION";
const UPDATE_WATER_REMINDER_NOTIFICATION = "UPDATE_WATER_REMINDER_NOTIFICATION";
const DELETE_WATER_REMINDER_NOTIFICATION_LIST =
  "DELETE_WATER_REMINDER_NOTIFICATION_LIST";

const CREATE_WORKOUT = "CREATE_WORKOUT";
const UPDATE_WORKOUT = "UPDATE_WORKOUT";
const DELETE_WORKOUT = "DELETE_WORKOUT";

const CREATE_CUP_DRUNK = "CREATE_CUP_DRUNK";
const UPDATE_CUP_DRUNK = "UPDATE_CUP_DRUNK";
const DELETE_CUP_DRUNK = "DELETE_CUP_DRUNK";

const CREATE_MEAL = "CREATE_MEAL";
const UPDATE_MEAL = "UPDATE_MEAL";
const DELETE_MEAL = "DELETE_MEAL";

const CREATE_DISH = "CREATE_DISH";
const UPDATE_DISH = "UPDATE_DISH";
const DELETE_DISH = "DELETE_DISH";

const CREATE_FOOD = "CREATE_FOOD";
const UPDATE_FOOD = "UPDATE_FOOD";
const DELETE_FOOD = "DELETE_FOOD";

const CREATE_DISH_FOOD = "CREATE_DISH_FOOD";
const UPDATE_DISH_FOOD = "UPDATE_DISH_FOOD";
const DELETE_DISH_FOOD = "DELETE_DISH_FOOD";

const CREATE_MEAL_FOOD = "CREATE_MEAL_FOOD";
const UPDATE_MEAL_FOOD = "UPDATE_MEAL_FOOD";
const DELETE_MEAL_FOOD = "DELETE_MEAL_FOOD";

const CREATE_MEAL_DISH = "CREATE_MEAL_DISH";
const DELETE_MEAL_DISH = "DELETE_MEAL_DISH";

const SET_TRUE_SHOW_FAB = "SET_TRUE_SHOW_FAB";
const SET_FALSE_SHOW_FAB = "SET_FALSE_SHOW_FAB";

const SET_SELECTED_DAY = "SET_SELECTED_DAY";

const DELETE_ALL_DATA = "DELETE_ALL_DATA";

export {
  SET_SELECTED_DAY,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
  CREATE_MEAL,
  UPDATE_MEAL,
  DELETE_MEAL,
  CREATE_WATER_REMINDER_NOTIFICATION,
  CREATE_WATER_REMINDER_NOTIFICATION_LIST,
  UPDATE_WATER_REMINDER_NOTIFICATION,
  DELETE_WATER_REMINDER_NOTIFICATION,
  DELETE_WATER_REMINDER_NOTIFICATION_LIST,
  CREATE_DAILY_NUTRITION,
  UPDATE_DAILY_NUTRITION,
  CREATE_WATER_INTAKE,
  UPDATE_WATER_INTAKE,
  CREATE_CUP_DRUNK,
  UPDATE_CUP_DRUNK,
  DELETE_CUP_DRUNK,
  CREATE_DISH,
  DELETE_DISH,
  UPDATE_DISH,
  CREATE_FOOD,
  UPDATE_FOOD,
  DELETE_FOOD,
  CREATE_DISH_FOOD,
  UPDATE_DISH_FOOD,
  DELETE_DISH_FOOD,
  CREATE_MEAL_FOOD,
  UPDATE_MEAL_FOOD,
  DELETE_MEAL_FOOD,
  CREATE_MEAL_DISH,
  DELETE_MEAL_DISH,
  SET_TRUE_SHOW_FAB,
  SET_FALSE_SHOW_FAB,
  CREATE_WORKOUT,
  UPDATE_WORKOUT,
  DELETE_WORKOUT,
  DELETE_ALL_DATA,
};
